import React from 'react';
    import { Check, Star } from 'lucide-react';

    export const plansData = {
        monthly: [
          {
            planId: 1,
            title: 'Plan Gratuito',
            subtitle: 'La información esencial, al instante.',
            price: 'Gratis',
            priceDetail: '',
            buttonText: 'Crear cuenta gratis',
            highlight: false,
            buttonVariant: 'secondary',
            benefits: [
              { text: 'Búsqueda ilimitada de medicamentos.', icon: <Check className="h-5 w-5 text-green-500" /> },
              { text: 'Obtención de la ficha simplificada y validada.', icon: <Check className="h-5 w-5 text-green-500" /> },
            ],
          },
          {
            planId: 2,
            title: 'Plan Personal',
            subtitle: 'Toma las riendas de tu propio tratamiento.',
            price: '$4.990',
            priceDetail: '/ mes',
            specialOffer: '¡Pruébalo GRATIS por 7 días!',
            offerNote: '(se requiere tarjeta)',
            buttonText: 'Comenzar mis 7 días gratis',
            highlight: false,
            buttonVariant: 'default',
            buttonColor: 'bg-green-500 hover:bg-green-600',
            benefits: [
              { text: 'Botiquín Virtual (1 perfil).', icon: <Star className="h-5 w-5 text-yellow-400" /> },
              { text: 'Alertas de Interacción.', icon: <Star className="h-5 w-5 text-yellow-400" /> },
              { text: 'Recordatorios de Tomas.', icon: <Star className="h-5 w-5 text-yellow-400" /> },
              { text: 'Perfil Exportable a PDF.', icon: <Star className="h-5 w-5 text-yellow-400" /> },
            ],
          },
          {
            planId: 3,
            title: 'Plan Familiar',
            subtitle: 'Cuidar de tus seres queridos con total seguridad.',
            price: '$7.990',
            priceDetail: '/ mes',
            tag: 'La más elegida por cuidadores',
            buttonText: 'Proteger a mi familia ahora',
            highlight: true,
            buttonVariant: 'default',
            buttonColor: 'bg-blue-800 hover:bg-blue-900',
            benefits: [
              { text: 'Todo lo del Plan Personal.', icon: <Star className="h-5 w-5 text-yellow-400" /> },
              { text: 'Gestión de Múltiples Perfiles (hasta 3).', icon: <Star className="h-5 w-5 text-yellow-400" /> },
              { text: 'Acceso a Comunidad Privada.', icon: <Star className="h-5 w-5 text-yellow-400" /> },
              { text: 'Soporte Prioritario.', icon: <Star className="h-5 w-5 text-yellow-400" /> },
            ],
          },
        ],
        annually: [
            {
                planId: 1,
                title: 'Plan Gratuito',
                subtitle: 'La información esencial, al instante.',
                price: 'Gratis',
                priceDetail: '',
                buttonText: 'Crear cuenta gratis',
                highlight: false,
                buttonVariant: 'secondary',
                benefits: [
                  { text: 'Búsqueda ilimitada de medicamentos.', icon: <Check className="h-5 w-5 text-green-500" /> },
                  { text: 'Obtención de la ficha simplificada y validada.', icon: <Check className="h-5 w-5 text-green-500" /> },
                ],
            },
            {
                planId: 4,
                title: 'Plan Personal',
                subtitle: 'Toma las riendas de tu propio tratamiento.',
                price: '$49.900',
                priceDetail: '/ año',
                specialOffer: '¡Pruébalo GRATIS por 7 días!',
                offerNote: '(se requiere tarjeta)',
                buttonText: 'Comenzar mis 7 días gratis',
                highlight: false,
                buttonVariant: 'default',
                buttonColor: 'bg-green-500 hover:bg-green-600',
                benefits: [
                  { text: 'Botiquín Virtual (1 perfil).', icon: <Star className="h-5 w-5 text-yellow-400" /> },
                  { text: 'Alertas de Interacción.', icon: <Star className="h-5 w-5 text-yellow-400" /> },
                  { text: 'Recordatorios de Tomas.', icon: <Star className="h-5 w-5 text-yellow-400" /> },
                  { text: 'Perfil Exportable a PDF.', icon: <Star className="h-5 w-5 text-yellow-400" /> },
                ],
            },
            {
                planId: 5,
                title: 'Plan Familiar',
                subtitle: 'Cuidar de tus seres queridos con total seguridad.',
                price: '$79.900',
                priceDetail: '/ año',
                tag: 'La más elegida por cuidadores',
                buttonText: 'Proteger a mi familia ahora',
                highlight: true,
                buttonVariant: 'default',
                buttonColor: 'bg-blue-800 hover:bg-blue-900',
                benefits: [
                  { text: 'Todo lo del Plan Personal.', icon: <Star className="h-5 w-5 text-yellow-400" /> },
                  { text: 'Gestión de Múltiples Perfiles (hasta 3).', icon: <Star className="h-5 w-5 text-yellow-400" /> },
                  { text: 'Acceso a Comunidad Privada.', icon: <Star className="h-5 w-5 text-yellow-400" /> },
                  { text: 'Soporte Prioritario.', icon: <Star className="h-5 w-5 text-yellow-400" /> },
                ],
            },
        ]
    };